### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by ricmik** [thomasloven/hass_plejd#41]
Is there a way to turn on / turn off / change brightness and temperature with a transition time?

The Plejd app has this ability through schedules, and I was hoping there is a way to set a transition time directly when communicating with the device.

**Comment by thomasloven** [comment]
There is not, unfortunately. The transition is part of the schedule itself that's programmed into the device from the app and there seems to be no way to send a "turn on with transition" command directly to a device.

Some plejd integrations do provide transitions, but that's done by bussy-waiting, i.e. the integration sends a dim level, waits a bit, sends another dim level etc. I will not implement a similar function since that would be very taxing on cpu time.
